---
env:
  global:
  - secure: |-
      TjX3/vpdSIJYLxFn5jLavW9Hl+0z5S/P/5WBmaCb/w/NiF7gPUxnhGPSx8qx
      sjOmcuiPXAd+/adyAjK4boajl1QUxfdf5cDD5ArvHR7zf0MpkIp02oIe7Vvx
      Dy7k3gFO/1g5g8kCOQF63N9vA6jvNLcojnK4p4vKm0mf2sAGH0g=
rvm:
- 2.0.0
branches:
  only:
  - master
script: ruby ci.rb travis
after_success:
- sh ruby ci.rb travis_deploy
